version: "3"
services:
  api:
    image: movies-api
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
