###All movies

GET http://localhost:3000/movies


###Movie by id
GET http://localhost:3000/movies/3


###Delete movie by id
DELETE  http://localhost:3000/movies/3

###Create movie
POST http://localhost:3000/movies

Content-Type: application/json
{
    "title": "Jason bourn",
    "duration": "120 menit"
}


###
PUT http://localhost:3000/movies/1

Content-Type: application/json
{
    "title": "Jason bourn",
    "duration": "120 menit"
}



